import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import TodoForm from '../components/TodoForm';
import TodoList from '../components/TodoList';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';

const Home = ({ todos }: any) => {
  const parsedTodos = JSON.parse(todos);
  return (
    <div className='max-w-[1000px] m-auto bg-gray-50'>
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className='border-b'>
        <TodoForm />
        <TodoList todos={parsedTodos} />
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const connectionString = process.env.DATABASE_URL;
  const pool = new Pool({ connectionString });
  const adapter = new PrismaPg(pool);
  const prisma = new PrismaClient({ adapter });

  try {
    const data = await prisma.todo.findMany();
    return { props: { todos: JSON.stringify(data || []) } };
  } catch (error) {
    console.error("DATABASE ERROR:", error);
    return { props: { todos: JSON.stringify([]) } };
  } finally {
    await prisma.$disconnect();
  }
};


export default Home;
